#!/bin/bash
#final
#cuffmerge 2

cd Cuffmerge &&

cuffmerge -g /home/bsc10/SRP/Pipeline5/This/rn6_refseq_rename.gtf -p 3 /home/bsc10/SRP/Pipeline5/Final/cuffmerge_wreference/merge &&

cd ../Cuffdiff &&

cuffdiff -p 3 /home/bsc10/SRP/Pipeline5/This/Cuffmerge/merged_asm/merged.gtf -L Controls,GEM /home/bsc10/SRP/Pipeline5/24/Tophat/tophat_out/accepted_hits.bam,/home/bsc10/SRP/Pipeline5/35/Tophat/tophat_out/accepted_hits.bam /home/bsc10/SRP/Pipeline5/59/Tophat/tophat_out/accepted_hits.bam 
